name: 'Canary Release'
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
  workflow_dispatch:
name: Canary Release
jobs:
  canary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
	uses: actions/checkout@v2

      - name: staging -> canary
        uses: robotology/gh-action-nightly-merge@v1.3.2
        with:
          stable_branch: staging
          development_branch: canary
          allow_ff: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
