on:
  push:
    branches:
      - staging
  workflow_dispatch:
name: Staging Release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        with:
          release-type: node
          package-name: testworkflow
          default-branch: staging
