on:
  push:
    branches:
      - staging
  workflow_dispatch:
name: Staging Release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        with:
          release-type: node
          package-name: testworkflow
          default-branch: staging
       - uses: actions/checkout@v2
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ steps.release.outputs.release_created }}
       - name: staging -> canary
      	uses: robotology/gh-action-nightly-merge@v1.3.1
        with:
          stable_branch: canary
          development_branch: staging
          allow_ff: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
	if: ${{ steps.release.outputs.release_created }}
